/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AttachmentObjectPageObjectPage journey");

        opaTest("Navigate to AttachmentObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheAttachmentListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheAttachmentListGenerated.onTable().iCheckRows();
            When.onTheAttachmentListGenerated.onTable().iPressRow(0);

            Then.onTheAttachmentObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the GeneralInfo section of the Object Page", function (_Given, _When, Then) {
            Then.onTheAttachmentObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheAttachmentObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "UUID" });
            Then.onTheAttachmentObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Description" });
            Then.onTheAttachmentObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LocalCreatedBy" });
            Then.onTheAttachmentObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LocalCreatedAt" });
            Then.onTheAttachmentObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LocalLastChangedBy" });
            Then.onTheAttachmentObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LocalLastChangedAt" });
            Then.onTheAttachmentObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChangedAt" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});