/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AttachmentListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheAttachmentListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheAttachmentListGenerated.onFilterBar().iCheckFilterField({ property: "UUID" });
            Then.onTheAttachmentListGenerated.onFilterBar().iCheckFilterField({ property: "Description" });
            Then.onTheAttachmentListGenerated.onFilterBar().iCheckFilterField({ property: "LocalCreatedBy" });
            Then.onTheAttachmentListGenerated.onFilterBar().iCheckFilterField({ property: "LocalCreatedAt" });
            Then.onTheAttachmentListGenerated.onFilterBar().iCheckFilterField({ property: "LocalLastChangedBy" });
            Then.onTheAttachmentListGenerated.onFilterBar().iCheckFilterField({ property: "LocalLastChangedAt" });
            Then.onTheAttachmentListGenerated.onFilterBar().iCheckFilterField({ property: "LastChangedAt" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheAttachmentListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheAttachmentListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheAttachmentListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheAttachmentListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheAttachmentListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheAttachmentListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"UUID":{"header":"UUID"},"Description":{"header":"Description"},"LocalCreatedBy":{"header":"Created By"},"LocalCreatedAt":{"header":"Created On"},"LocalLastChangedBy":{"header":"Changed By"},"LocalLastChangedAt":{"header":"Changed On"},"LastChangedAt":{"header":"Changed On"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheAttachmentListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheAttachmentListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheAttachmentListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheAttachmentObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});